### ISSUE TITLE
Mobile: About section

### ISSUE THREAD

**Issue by kittyboom** [loudrabbits/fizz#10]
Please can you move the 'about' text down, it is currently touching the bottom of the carousel.

**Comment by ronalochner** [comment]
Done

**Comment by ronalochner** [comment]
Added spacing above to all the sections not just about, @kittyboom can you check if you think it needs spacing at the bottom too so that it doesnt look lobsided?

**Comment by kittyboom** [comment]
The top appears to be perfect - can we add the same to the bottom. 

We must just double check where the anchor goes once you get the drop down working.
