### ISSUE TITLE
Mobile: Scrolling

### ISSUE THREAD

**Issue by kittyboom** [loudrabbits/fizz#11]
There are some major issues with scrolling at the moment. Please fix the overflow issues. Sections are scrolling into one another and getting stuck. *Feel free to blame and moan at Steven for this one.

**Comment by ronalochner** [comment]
haha :) I think this is fixed?

**Comment by kittyboom** [comment]
Mobile - The only issue I see here now is that the screen moving in all directions as I try to scroll.

**Comment by eksoverzero** [comment]
@ronalochner. I was this the other day. The easiest fix is to set to toggler button to `position: fixed` instead of `absolute` and then set the horizontal scroll overflow to hidden

**Comment by ronalochner** [comment]
@eksoverzero 

CSS

.navbar-toggler {
  position: fixed;
}

JS
    scrollOverflow: false,
  

Like this?
