### ISSUE TITLE
Change: New About Text

### ISSUE THREAD

**Issue by KerryHugill** [loudrabbits/fizz#17]
Change About text to the below. (Very strange text. Are they sure this is what they want?)

Great! You wanna know what Fizz is about? Pretty straight-forward it’s about real taste & less is more.

WTFizz?! Our sodas are hand crafted with just a few ingredients and no bullshit because we don’t like it. We don't use preservatives, flavourings and chemicals. Why should we, if we get all the real and authentic taste for our Fizz from Mother Nature. Only fruits grown by our South African farmers make it into our bottles - apples from the Elgin Valley, grapes from Stellenbosch and pineapples from Bathurst. Fruits get pressed right where they are picked, then get bottled and capped in small batches in Cape Town. Easy to see and taste where that genuine quality comes from.

Less is more - Quality fruit juice straight from the press with a dash of carbonated water and sparkle that fizzes you up! A refreshment that takes you back to the real flavours of Apple, Red Grape and Pineapple. FIZZ Cooldrinks is brought to you by the Cape Town Cool Drink Company, the makers of Juicebox. 

We love the original, real fruit taste – Local is Lekker! It’s simple.
--

**Comment by kittyboom** [comment]
The client is rewriting this so we will have to hold on this till I get something from him.

**Comment by ronalochner** [comment]
Done

**Comment by kittyboom** [comment]
This is great but we need to shorten the length of the paragraphs. Can we make the paragraphs the same width as the first sentence " Great! ...less is more."
