### ISSUE TITLE
Change: "What the Fizz?" to WTFIZZ

### ISSUE THREAD

**Issue by KerryHugill** [loudrabbits/fizz#19]
‘What the Fizz?’ to change to WTFIZZ  & no question mark.

**Comment by ronalochner** [comment]
Done

**Comment by kittyboom** [comment]
Please add an even amount of padding to top and bottom, and left and right. 

We also will need to make these a little bit bigger. (Guestimation - 120%).

**Comment by ronalochner** [comment]
@kittyboom It is centered to the screen at the moment. Do you want to center it to the picture area excluding the nav? So a little lower?

**Comment by kittyboom** [comment]
Yes please

**Comment by ronalochner** [comment]
Done
