### ISSUE TITLE
Website & Mobile: Carousel needs to continuously scroll

### ISSUE THREAD

**Issue by eksoverzero** [loudrabbits/fizz#3]
Right now, the custom after action is pushing the slides using the index. By setting fullPage.js to use continuous horizontal scrolling and then, in the callback, using `.nextSlide()` should fix this.

**Comment by eksoverzero** [comment]
fullPage.js has support for this, but it is a paid extension. Before going there, maybe try remove the fullPage.js slides and use this: http://archive.nicinabox.com/superslides/#1

Branch off for this so that if it doesn't work, you won't have lost your work

**Comment by KerryHugill** [comment]
@eksoverzero Rona tried to work on this, based on your instructions, but couldn't get it to work. Please can you take a look :)
