### ISSUE TITLE
Website: Apple Flavour Text

### ISSUE THREAD

**Issue by kittyboom** [loudrabbits/fizz#6]
In the grape flavour blurb please can you change non - alcoholic to non-alcoholic.
*Just remove the spaces on either side of the hyphen.

Please change South Africa's to South Africas' *move apostrophe to after 's' of Africas

**Comment by ronalochner** [comment]
Done

**Comment by kittyboom** [comment]
<img width="938" alt="screen shot 2018-03-14 at 4 03 41 pm" src="https://user-images.githubusercontent.com/37333247/37407029-5de7f33c-27a1-11e8-8a2c-f56a740cbed2.png">
Something is happening with  'Apple Fizz' please move it to the right so that it is not cut off. Also, to make all the flavours look the same now - The blurb (body copy) for Apple needs to move slightly to the left. You can see the gap here now looks a little bigger than the rest.

**Comment by ronalochner** [comment]
@kittyboom I don't know what you mean by cut-off. On my screen its the same as the other ones. I took off all the padding on the left of the blurb. It's the image pushing it. So we would need to export it with less transparent space. Unless @eksoverzero has a better idea?

**Comment by KerryHugill** [comment]
This may have resolved with flavour order change. But please check all spacing and gaps are the same from one flavour to the next @rona. 

If it’s a case of exporting or cropping the image - you can do that in psd quite quickly.

**Comment by ronalochner** [comment]
Okay I think this is resolved

**Comment by ronalochner** [comment]
@kittyboom can you check if you are happy with how i canged this?
